/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./login.html",
    "./signup.html",
    "./app.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#81ecff",
        "surface-dim": "#060e20",
        "error": "#ff716c",
        "on-secondary": "#004d58",
        "on-primary-fixed": "#003840",
        "on-background": "#dee5ff",
        "tertiary-container": "#2778fe",
        "primary": "#81ecff",
        "surface-container-low": "#091328",
        "outline": "#6d758c",
        "on-tertiary": "#001d4e",
        "surface-container-high": "#141f38",
        "on-primary-container": "#004d57",
        "error-container": "#9f0519",
        "on-secondary-container": "#e9fbff",
        "surface-container": "#0f1930",
        "tertiary": "#6e9bff",
        "surface": "#060e20",
        "secondary-container": "#006876",
        "primary-fixed": "#00e3fd",
        "on-error": "#490006",
        "secondary-fixed": "#54e3fc",
        "inverse-surface": "#faf8ff",
        "on-surface-variant": "#a3aac4",
        "surface-bright": "#1f2b49",
        "on-tertiary-fixed-variant": "#003580",
        "on-tertiary-container": "#000000",
        "on-primary": "#005762",
        "on-secondary-fixed": "#003a43",
        "background": "#060e20",
        "primary-dim": "#00d4ec",
        "tertiary-fixed-dim": "#77a1ff",
        "secondary-dim": "#3cd2eb",
        "primary-fixed-dim": "#00d4ec",
        "on-primary-fixed-variant": "#005762",
        "on-surface": "#dee5ff",
        "inverse-on-surface": "#4d556b",
        "secondary-fixed-dim": "#40d5ee",
        "surface-variant": "#192540",
        "on-error-container": "#ffa8a3",
        "outline-variant": "#40485d",
        "on-tertiary-fixed": "#00163d",
        "inverse-primary": "#006976",
        "surface-container-lowest": "#000000",
        "secondary": "#50e1f9",
        "on-secondary-fixed-variant": "#005965",
        "tertiary-fixed": "#8eafff",
        "tertiary-dim": "#0f6df3",
        "primary-container": "#00e3fd",
        "surface-container-highest": "#192540",
        "error-dim": "#d7383b"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Space Grotesk"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
